model: "tic_hp"
dataset: "flicker"
dataset_path: "path/to/training/set"
kodak_path: 'path/to/kodak/dataset'
epochs: 400
learning_rate: 1.e-4
num_workers: 4
quality_level: 4 # {1,2,3,4}
lmbda: 0.013 # {0.0018, 0.0035, 0.0067, 0.013}
batch_size: 12
test_batch_size: 1
aux_learning_rate: 1.e-3
patch_size: 256
cuda: True
gpu_id: 0
save: True
clip_max_norm: 1.0
root: '/root/path'
name: "NAME"
exp_name: "comet experiment name"
seed: 42
checkpoint: